tages:

  - build

  - test

  - package

 

variables:

  PACKAGE_NAME: "longest-words"

  VERSION: "1.0"

 

# Этап сборки

build:

  stage: build

  script:

    - echo "Сборка ПО"

    - chmod +x cicd/build.sh

    - ./cicd/build.sh

  artifacts:

    paths:

      - usr/bin/longest_words

 

# Этап тестирования

test:

  stage: test

  script:

    - echo "Тестирование ПО"

    - chmod +x cicd/test.sh

    - ./cicd/test.sh

 

# Этап упаковки

package:

  stage: package

  script:

    - echo "Упаковка в .deb пакет"

    - chmod +x cicd/package.sh

    - ./cicd/package.sh

  artifacts:

    paths:

      - *.deb
